version: '3.8'

services:
  drawing-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app/src
    environment:
      - NODE_ENV=production
