name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/drawing-app
  HOST_IP: ${{ secrets.HOST_IP }}
  HOST_USER: ${{ secrets.HOST_USER }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

    - name: Deploy to host
      run: |
        ssh ${{ env.HOST_USER }}@${{ env.HOST_IP }} "
          # Pull the latest image
          docker pull ${{ env.DOCKER_IMAGE }}:latest

          # Stop and remove the existing container (if it exists)
          docker stop my-website-container || true
          docker rm my-website-container || true

          # Run the new container
          docker run -d \
            --name my-website-container \
            --restart unless-stopped \
            -p 80:80 \
            ${{ env.DOCKER_IMAGE }}:latest
        "